#server.port=8085
#spring.application.name=API-GATEWAY-SERVICE
#
## Gateway Route using Eureka Discovery
#spring.cloud.gateway.routes[0].id=employee-service
#spring.cloud.gateway.routes[0].uri=lb://employee-service
#spring.cloud.gateway.routes[0].predicates=Path=/api/employee/**
#spring.cloud.gateway.routes[0].filters=RewritePath=/api/employee/(?<segment>.*),/employee-service/api/employee/${segment}
#
#spring.cloud.gateway.routes[1].id=address-service
#spring.cloud.gateway.routes[1].uri=lb://address-service
#spring.cloud.gateway.routes[1].predicates=Path=/api/address/**
#spring.cloud.gateway.routes[1].filters=RewritePath=/api/address/(?<segment>.*),/address-service/api/address/${segment}
#
#
## Enable Service Discovery
#spring.cloud.discovery.enabled=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.enabled=true
#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.application.name}:8085
#eureka.instance.lease-renewal-interval-in-seconds=5
#eureka.instance.lease-expiration-duration-in-seconds=10
#logging.level.org.springframework.cloud.gateway=DEBUG
#logging.level.org.springframework.cloud.loadbalancer=DEBUG
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.hostname=localhost
server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employee/**
          filters:
            - RewritePath=/api/employee/(?<segment>.*),/employee-service/api/employee/${segment}
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/address/**
          filters:
            - RewritePath=/api/address/(?<segment>.*),/address-service/api/address/${segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:8085
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
